# Configuration settings for real_time_stream package

# Replace with your actual Fyers access token.
FYERS_TOKEN = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJhcGkuZnllcnMuaW4iLCJpYXQiOjE3NDAxMTM0NTYsImV4cCI6MTc0MDE4NDI1NiwibmJmIjoxNzQwMTEzNDU2LCJhdWQiOlsieDowIiwieDoxIiwieDoyIiwiZDoxIiwiZDoyIiwieDoxIiwieDowIiwieDoxIiwieDowIiwieDoxIiwieDowIl0sInN1YiI6ImFjY2Vzc190b2tlbiIsImF0X2hhc2giOiJnQUFBQUFCbnVBWXdybHVSSkR1UUtaYzUxNXd1S0VUZi1fU05MbTB3aGtmeWJrYmJQVzJJNDhxRFBlRlVGdlp5ckpJMkk4WHB0OFB0QWNzWTMwMlpwOWRfLTZEc3RGcFVjbU9keV9XMWZIYURRVHZGSjJtRVE1dz0iLCJkaXNwbGF5X25hbWUiOiJNVUtFU0ggUkFNTEFMIFZJU0hXQUtBUk1BIiwib21zIjoiSzEiLCJoc21fa2V5IjoiMGE1ZjE5YWNkZjM5NTk5ZjBhMjI1MTExNjE3YzYyMWY2MGFkNTFkOTg0N2ExMDc3NTZmZjhiNDkiLCJpc0RkcGlFbmFibGVkIjoiTiIsImlzTXRmRW5hYmxlZCI6Ik4iLCJmeV9pZCI6IllNMjg0MTIiLCJhcHBUeXBlIjoxMDAsInBvYV9mbGFnIjoiTiJ9.z5GG2P9yS8qJ2D9YGV270ccyJHFv-nfd6ovt5RiE_x8"

# Binance symbols (in lowercase)
BINANCE_SYMBOLS = ["btcusdt", "ethusdt"]

binance_api_key: "LYEu4haYVMKq6eLwZRL6abbaM3MYoHQnI9xGmF2NgIKG5QQIb0uFl3hrxiPTKext"
binance_api_secret: "UuXHuMrJ7mZiyDuQCNsbKOAA5y72uB6tXVAHYwa3iEKXvNzOIW6SkbvtMVUBvha1"
