"""Initial migration

Revision ID: ff45319d0747
Revises: 
Create Date: 2025-02-20 17:22:00.385549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff45319d0747'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RealTimeData',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('high_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('low_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('close_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'date', 'time'),
    sa.UniqueConstraint('symbol', 'date', 'time', name='unique_symbol_datetime')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RealTimeData')
    # ### end Alembic commands ###
